# ABOUTME: PrusaSlicer->Orca key maps, drop allowlist, preset pairs, and value transforms
# ABOUTME: for the CORE One INDX 8T port. None = intentionally dropped (reason in ALLOWLIST).

MACHINE_MAP = {
    "bed_shape": "printable_area",
    "max_print_height": "printable_height",
    "nozzle_diameter": "nozzle_diameter",
    "max_layer_height": "max_layer_height",
    "min_layer_height": "min_layer_height",
    "extruder_colour": "extruder_colour",
    "extruder_offset": "extruder_offset",
    "retract_length": "retraction_length",
    "retract_speed": "retraction_speed",
    "deretract_speed": "deretraction_speed",
    "retract_before_travel": "retraction_minimum_travel",
    "retract_before_wipe": "retract_before_wipe",
    "retract_layer_change": "retract_when_changing_layer",
    "retract_length_toolchange": "retract_length_toolchange",
    "retract_restart_extra": "retract_restart_extra",
    "retract_restart_extra_toolchange": "retract_restart_extra_toolchange",
    "retract_lift": "z_hop",
    "retract_lift_above": "retract_lift_above",
    "retract_lift_below": "retract_lift_below",
    "wipe": "wipe",
    "machine_max_acceleration_e": "machine_max_acceleration_e",
    "machine_max_acceleration_extruding": "machine_max_acceleration_extruding",
    "machine_max_acceleration_retracting": "machine_max_acceleration_retracting",
    "machine_max_acceleration_travel": "machine_max_acceleration_travel",
    "machine_max_acceleration_x": "machine_max_acceleration_x",
    "machine_max_acceleration_y": "machine_max_acceleration_y",
    "machine_max_acceleration_z": "machine_max_acceleration_z",
    "machine_max_feedrate_e": "machine_max_speed_e",
    "machine_max_feedrate_x": "machine_max_speed_x",
    "machine_max_feedrate_y": "machine_max_speed_y",
    "machine_max_feedrate_z": "machine_max_speed_z",
    "machine_max_jerk_e": "machine_max_jerk_e",
    "machine_max_jerk_x": "machine_max_jerk_x",
    "machine_max_jerk_y": "machine_max_jerk_y",
    "machine_max_jerk_z": "machine_max_jerk_z",
    "machine_max_junction_deviation": "machine_max_junction_deviation",
    "machine_min_extruding_rate": "machine_min_extruding_rate",
    "machine_min_travel_rate": "machine_min_travel_rate",
    "cooling_tube_length": "cooling_tube_length",
    "cooling_tube_retraction": "cooling_tube_retraction",
    "parking_pos_retraction": "parking_pos_retraction",
    "extra_loading_move": "extra_loading_move",
    "high_current_on_filament_swap": "high_current_on_filament_swap",
    "single_extruder_multi_material": "single_extruder_multi_material",
    "use_firmware_retraction": "use_firmware_retraction",
    "use_relative_e_distances": "use_relative_e_distances",
    "gcode_flavor": "gcode_flavor",
    "host_type": "host_type",
    "thumbnails": "thumbnails",
    "thumbnails_format": "thumbnails_format",
    "extruder_clearance_radius": "extruder_clearance_radius",
    "extruder_clearance_height": "extruder_clearance_height_to_rod",
    "machine_limits_usage": "emit_machine_limits_to_gcode",
    "z_offset": "z_offset",
    "pause_print_gcode": "machine_pause_gcode",
    "autoemit_temperature_commands": None,
    "binary_gcode": None,
    "color_change_gcode": None,
    "multimaterial_purging": None,
    "prefer_clockwise_movements": None,
    "printer_technology": None,
    "remaining_times": None,
    "silent_mode": None,
    "travel_lift_before_obstacle": None,
    "travel_max_lift": None,
    "travel_ramping_lift": None,
    "travel_slope": None,
    "use_volumetric_e": None,
    "variable_layer_height": None,
    "nozzle_high_flow": None,
    "default_filament_profile": None,
    "default_print_profile": None,
    "printer_model": None,
    "printer_variant": None,
    "printer_notes": None,
    "start_gcode": None,
    "end_gcode": None,
    "toolchange_gcode": None,
    "layer_gcode": None,
    "before_layer_gcode": None,
}

PROCESS_MAP = {
    "layer_height": "layer_height",
    "first_layer_height": "initial_layer_print_height",
    "perimeters": "wall_loops",
    "top_solid_layers": "top_shell_layers",
    "bottom_solid_layers": "bottom_shell_layers",
    "top_solid_min_thickness": "top_shell_thickness",
    "bottom_solid_min_thickness": "bottom_shell_thickness",
    "extrusion_width": "line_width",
    "perimeter_extrusion_width": "inner_wall_line_width",
    "external_perimeter_extrusion_width": "outer_wall_line_width",
    "infill_extrusion_width": "sparse_infill_line_width",
    "solid_infill_extrusion_width": "internal_solid_infill_line_width",
    "top_infill_extrusion_width": "top_surface_line_width",
    "first_layer_extrusion_width": "initial_layer_line_width",
    "support_material_extrusion_width": "support_line_width",
    "perimeter_speed": "inner_wall_speed",
    "external_perimeter_speed": "outer_wall_speed",
    "small_perimeter_speed": "small_perimeter_speed",
    "infill_speed": "sparse_infill_speed",
    "solid_infill_speed": "internal_solid_infill_speed",
    "top_solid_infill_speed": "top_surface_speed",
    "first_layer_speed": "initial_layer_speed",
    "first_layer_infill_speed": "initial_layer_infill_speed",
    "bridge_speed": "bridge_speed",
    "gap_fill_speed": "gap_infill_speed",
    "support_material_speed": "support_speed",
    "support_material_interface_speed": "support_interface_speed",
    "travel_speed": "travel_speed",
    "travel_speed_z": "travel_speed_z",
    "default_acceleration": "default_acceleration",
    "perimeter_acceleration": "inner_wall_acceleration",
    "external_perimeter_acceleration": "outer_wall_acceleration",
    "infill_acceleration": "sparse_infill_acceleration",
    "solid_infill_acceleration": "internal_solid_infill_acceleration",
    "top_solid_infill_acceleration": "top_surface_acceleration",
    "first_layer_acceleration": "initial_layer_acceleration",
    "bridge_acceleration": "bridge_acceleration",
    "travel_acceleration": "travel_acceleration",
    "fill_density": "sparse_infill_density",
    "fill_pattern": "sparse_infill_pattern",
    "fill_angle": "infill_direction",
    "infill_overlap": "infill_wall_overlap",
    "infill_anchor": "infill_anchor",
    "infill_anchor_max": "infill_anchor_max",
    "top_fill_pattern": "top_surface_pattern",
    "bottom_fill_pattern": "bottom_surface_pattern",
    "enable_dynamic_overhang_speeds": "enable_overhang_speed",
    "overhang_speed_0": "overhang_1_4_speed",
    "overhang_speed_1": "overhang_2_4_speed",
    "overhang_speed_2": "overhang_3_4_speed",
    "overhang_speed_3": "overhang_4_4_speed",
    "seam_position": "seam_position",
    "elefant_foot_compensation": "elefant_foot_compensation",
    "gcode_resolution": "resolution",
    "arc_fitting": "enable_arc_fitting",
    "perimeter_generator": "wall_generator",
    "thin_walls": "detect_thin_wall",
    "overhangs": "detect_overhang_wall",
    "bridge_flow_ratio": "bridge_flow",
    "thick_bridges": "thick_bridges",
    "min_bead_width": "min_bead_width",
    "min_feature_size": "min_feature_size",
    "wall_distribution_count": "wall_distribution_count",
    "wall_transition_angle": "wall_transition_angle",
    "wall_transition_filter_deviation": "wall_transition_filter_deviation",
    "wall_transition_length": "wall_transition_length",
    "brim_type": "brim_type",
    "brim_width": "brim_width",
    "brim_separation": "brim_object_gap",
    "skirts": "skirt_loops",
    "skirt_distance": "skirt_distance",
    "skirt_height": "skirt_height",
    "support_material": "enable_support",
    "support_material_threshold": "support_threshold_angle",
    "support_material_angle": "support_angle",
    "support_material_contact_distance": "support_top_z_distance",
    "support_material_bottom_contact_distance": None,
    "support_material_interface_layers": "support_interface_top_layers",
    "support_material_bottom_interface_layers": "support_interface_bottom_layers",
    "support_material_interface_spacing": "support_interface_spacing",
    "support_material_interface_pattern": "support_interface_pattern",
    "support_material_pattern": "support_base_pattern",
    "support_material_spacing": "support_base_pattern_spacing",
    "support_material_style": "support_style",
    "support_material_xy_spacing": "support_object_xy_distance",
    "support_material_buildplate_only": "support_on_build_plate_only",
    "support_tree_angle": "tree_support_branch_angle",
    "support_tree_angle_slow": "tree_support_angle_slow",
    "support_tree_branch_diameter": "tree_support_branch_diameter",
    "support_tree_branch_diameter_angle": "tree_support_branch_diameter_angle",
    "support_tree_branch_diameter_double_wall": "tree_support_branch_diameter_double_wall",
    "support_tree_branch_distance": "tree_support_branch_distance",
    "support_tree_tip_diameter": "tree_support_tip_diameter",
    "support_tree_top_rate": "tree_support_top_rate",
    "raft_contact_distance": "raft_contact_distance",
    "raft_expansion": "raft_expansion",
    "raft_first_layer_density": "raft_first_layer_density",
    "raft_first_layer_expansion": "raft_first_layer_expansion",
    "wipe_tower": "enable_prime_tower",
    "wipe_tower_width": "prime_tower_width",
    "wipe_tower_cone_angle": "wipe_tower_cone_angle",
    "wipe_tower_extra_spacing": "wipe_tower_extra_spacing",
    "wipe_tower_extra_flow": "wipe_tower_extra_flow",
    "wipe_tower_bridging": "wipe_tower_bridging",
    "wipe_tower_brim_width": "prime_tower_brim_width",
    "wipe_tower_no_sparse_layers": "wipe_tower_no_sparse_layers",
    "single_extruder_multi_material_priming": "single_extruder_multi_material_priming",
    "mmu_segmented_region_max_width": "mmu_segmented_region_max_width",
    "output_filename_format": None,
    "xy_size_compensation": "xy_size_compensation",
    "ensure_vertical_shell_thickness": "ensure_vertical_shell_thickness",
    "gcode_label_objects": "gcode_label_objects",
    "top_one_perimeter_type": "only_one_wall_top",
    "support_material_auto": None,
    "automatic_infill_combination_max_layer_height": None,
    "bridge_angle": None,
    "dont_support_bridges": None,
    "extra_perimeters": None,
    "external_perimeters_first": None,
    "first_layer_acceleration_over_raft": None,
    "first_layer_speed_over_raft": None,
    "gap_fill_enabled": None,
    "infill_every_layers": None,
    "infill_extruder": None,
    "perimeter_extruder": None,
    "solid_infill_extruder": None,
    "support_material_extruder": None,
    "support_material_interface_extruder": None,
    "infill_first": None,
    "max_print_speed": None,
    "max_volumetric_speed": None,
    "min_skirt_length": None,
    "notes": None,
    "over_bridge_speed": None,
    "solid_infill_below_area": None,
    "solid_infill_every_layers": None,
    "support_material_closing_radius": None,
    "support_material_enforce_layers": None,
    "support_material_interface_contact_loops": None,
    "support_material_synchronize_layers": None,
    "support_material_with_sheath": None,
    "toolchange_ordering": None,
    "travel_short_distance_acceleration": None,
    "wipe_tower_acceleration": None,
    "wipe_tower_extruder": None,
    "compatible_printers_condition": None,
}

FILAMENT_MAP = {
    "temperature": "nozzle_temperature",
    "first_layer_temperature": "nozzle_temperature_initial_layer",
    "bed_temperature": "hot_plate_temp",
    "first_layer_bed_temperature": "hot_plate_temp_initial_layer",
    "chamber_temperature": "chamber_temperature",
    "chamber_minimal_temperature": "chamber_minimal_temperature",
    "filament_max_volumetric_speed": "filament_max_volumetric_speed",
    "filament_minimal_purge_on_wipe_tower": "filament_minimal_purge_on_wipe_tower",
    "min_fan_speed": "fan_min_speed",
    "max_fan_speed": "fan_max_speed",
    "bridge_fan_speed": "overhang_fan_speed",
    "disable_fan_first_layers": "close_fan_the_first_x_layers",
    "fan_below_layer_time": "fan_cooling_layer_time",
    "slowdown_below_layer_time": "slow_down_layer_time",
    "min_print_speed": "slow_down_min_speed",
    "filament_retract_length": "filament_retraction_length",
    "filament_wipe": "filament_wipe",
    "filament_retract_before_wipe": "filament_retract_before_wipe",
    "filament_density": "filament_density",
    "filament_cost": "filament_cost",
    "extrusion_multiplier": "filament_flow_ratio",
    "filament_type": "filament_type",
    "filament_soluble": "filament_soluble",
    "filament_diameter": "filament_diameter",
    "filament_vendor": "filament_vendor",
    "start_filament_gcode": "filament_start_gcode",
    "end_filament_gcode": "filament_end_gcode",
    "filament_multitool_ramming": "filament_multitool_ramming",
    "filament_multitool_ramming_volume": "filament_multitool_ramming_volume",
    "filament_multitool_ramming_flow": "filament_multitool_ramming_flow",
    "filament_loading_speed": "filament_loading_speed",
    "filament_loading_speed_start": "filament_loading_speed_start",
    "filament_unloading_speed": "filament_unloading_speed",
    "filament_unloading_speed_start": "filament_unloading_speed_start",
    "filament_load_time": "filament_load_time",
    "filament_unload_time": "filament_unload_time",
    "filament_cooling_moves": "filament_cooling_moves",
    "filament_cooling_initial_speed": "filament_cooling_initial_speed",
    "filament_cooling_final_speed": "filament_cooling_final_speed",
    "filament_stamping_distance": "filament_stamping_distance",
    "filament_stamping_loading_speed": "filament_stamping_loading_speed",
    "filament_toolchange_delay": "filament_toolchange_delay",
    "filament_shrinkage_compensation_xy": "filament_shrink",
    "filament_shrinkage_compensation_z": "filament_shrinkage_compensation_z",
    "full_fan_speed_layer": "full_fan_speed_layer",
    "fan_always_on": "reduce_fan_stop_start_freq",
    "cooling": "slow_down_for_layer_cooling",
    "idle_temperature": "idle_temperature",
    "compatible_printers_condition": None,
    "cooling_perimeter_transition_distance": None,
    "cooling_slowdown_logic": None,
    "enable_dynamic_fan_speeds": None,
    "overhang_fan_speed_0": None,
    "overhang_fan_speed_1": None,
    "overhang_fan_speed_2": None,
    "overhang_fan_speed_3": None,
    "filament_abrasive": None,
    "filament_infill_max_speed": None,
    "filament_infill_max_crossing_speed": None,
    "filament_purge_multiplier": None,
    "filament_ramming_parameters": None,
    "filament_retract_length_toolchange": None,
    "filament_retract_lift": None,
    "filament_settings_id": None,
    "compatible_printers": None,
    "filament_travel_max_lift": "filament_z_hop",
    "filament_travel_ramping_lift": None,
    "filament_travel_slope": None,
    "filament_spool_weight": None,
    "filament_colour": None,
    "filament_notes": None,
    "renamed_from": None,
}

ALLOWLIST = {
    "autoemit_temperature_commands": "no Orca key; Orca always emits temperature commands itself",
    "binary_gcode": "Orca has no binary-gcode output",
    "color_change_gcode": "no Orca config key; M600 not used on a toolchanger",
    "multimaterial_purging": "no Orca key; purge volumes come from filament settings",
    "prefer_clockwise_movements": "no Orca key",
    "printer_technology": "implicit FFF in Orca machine profiles",
    "remaining_times": "no Orca key; firmware M73 always understood",
    "silent_mode": "deprecated/ignored in Orca (PrintConfig ignore set)",
    "travel_lift_before_obstacle": "Orca lift model is z_hop + z_hop_types",
    "travel_max_lift": "ported as literal Z1.5 in change_filament_gcode",
    "travel_ramping_lift": "expressed via z_hop_types Slope Lift",
    "travel_slope": "ported as literal A1 in change_filament_gcode",
    "use_volumetric_e": "no Orca key",
    "variable_layer_height": "no usable Orca key (adaptive_layer_height removed)",
    "nozzle_high_flow": "Orca convention: HF_NOZZLE keyword in printer_notes",
    "default_filament_profile": "names differ by design (checked by eye)",
    "default_print_profile": "names differ by design (checked by eye)",
    "printer_model": "names differ by design",
    "printer_variant": "PS HF0.4 vs Orca 0.4 by design (HF lives in the model name)",
    "printer_notes": "rewritten to Orca keyword conventions (adds HF_NOZZLE)",
    "start_gcode": "g-code compared by review, not value-diff",
    "end_gcode": "g-code compared by review, not value-diff",
    "toolchange_gcode": "g-code compared by review, not value-diff",
    "layer_gcode": "g-code compared by review, not value-diff",
    "before_layer_gcode": "g-code compared by review, not value-diff",
    "support_material_auto": "expressed via support_type normal(manual)",
    "support_material_bottom_contact_distance": "PS 0 = follow top distance; explicit Orca 0 would fuse supports",
    "output_filename_format": "PS format uses printing_filament_types (absent in Orca); inherit Orca default",
    "automatic_infill_combination_max_layer_height": "no Orca key",
    "bridge_angle": "PS 0 = auto = Orca default when key absent",
    "dont_support_bridges": "no matching Orca key; Orca default behavior",
    "extra_perimeters": "PS 0 = off = Orca default",
    "external_perimeters_first": "PS 0 = Orca default wall_sequence",
    "first_layer_acceleration_over_raft": "PS 0 = disabled; no Orca key",
    "first_layer_speed_over_raft": "no Orca key",
    "gap_fill_enabled": "PS 1 = Orca default (gap fill on)",
    "infill_every_layers": "PS 1 = no combining = Orca default",
    "infill_extruder": "PS 1 = default extruder assignment",
    "perimeter_extruder": "PS 1 = default extruder assignment",
    "solid_infill_extruder": "PS 1 = default extruder assignment",
    "support_material_extruder": "PS 0 = current extruder = Orca default",
    "support_material_interface_extruder": "PS 0 = current extruder = Orca default",
    "infill_first": "PS 0 = Orca default order",
    "max_print_speed": "no Orca key (auto from feature speeds)",
    "max_volumetric_speed": "PS 0 = unlimited = Orca default (filament caps apply)",
    "min_skirt_length": "skirts=0 makes it moot",
    "notes": "empty",
    "over_bridge_speed": "no Orca key",
    "solid_infill_below_area": "PS 0 = off = Orca default",
    "solid_infill_every_layers": "PS 0 = off = Orca default",
    "support_material_closing_radius": "no Orca key",
    "support_material_enforce_layers": "PS 0 = off",
    "support_material_interface_contact_loops": "PS 0 = off",
    "support_material_synchronize_layers": "PS 0 = off",
    "support_material_with_sheath": "PS 0 = off",
    "toolchange_ordering": "no Orca key (0.15mm DETAIL loses cyclic ordering)",
    "travel_short_distance_acceleration": "no Orca key",
    "wipe_tower_acceleration": "PS 0 = default accel; no Orca key",
    "wipe_tower_extruder": "PS 0 = auto = Orca default",
    "compatible_printers_condition": "replaced by compatible_printers array",
    "cooling_perimeter_transition_distance": "no Orca key",
    "cooling_slowdown_logic": "no Orca key",
    "enable_dynamic_fan_speeds": "Orca overhang fan model differs; overhang_fan_speed used",
    "overhang_fan_speed_0": "collapsed into overhang_fan_speed",
    "overhang_fan_speed_1": "collapsed into overhang_fan_speed",
    "overhang_fan_speed_2": "collapsed into overhang_fan_speed",
    "overhang_fan_speed_3": "collapsed into overhang_fan_speed",
    "filament_abrasive": "expressed as ABRASIVE keyword in filament_notes",
    "filament_infill_max_speed": "no Orca key",
    "filament_infill_max_crossing_speed": "no Orca key",
    "filament_purge_multiplier": "no Orca key (verified absent in PrintConfig.cpp)",
    "filament_ramming_parameters": "SEMM ramming; INDX uses multitool ramming keys",
    "filament_retract_length_toolchange": "no Orca key; g-code uses retract_length[] instead",
    "filament_travel_ramping_lift": "Orca model: filament_z_hop_types",
    "filament_retract_lift": "inert in PS INDX (ramping lift active); filament_travel_max_lift ports to filament_z_hop",
    "filament_settings_id": "PrusaSlicer bookkeeping key",
    "compatible_printers": "replaced by our explicit compatible_printers array",
    "filament_travel_slope": "Orca model: filament_z_hop_types",
    "filament_spool_weight": "no Orca key (verified absent in PrintConfig.cpp)",
    "filament_colour": "Orca Prusa filaments do not carry colour; omit",
    "filament_notes": "rewritten (ABRASIVE keyword only where needed)",
    "renamed_from": "PrusaSlicer bookkeeping key",
}

PAIRS = {
    "machine": [("Prusa CORE One INDX 8T HF0.4 nozzle", "Prusa CORE One INDX 8T 0.4 nozzle")],
    "process": [
        ("0.10mm Fine @COREONEINDX HF0.4", "0.10mm FINE @CORE One INDX 0.4"),
        ("0.15mm Detail @COREONEINDX HF0.4", "0.15mm DETAIL @CORE One INDX 0.4"),
        ("0.20mm Balanced ★ @COREONEINDX HF0.4", "0.20mm BALANCED @CORE One INDX 0.4"),
        ("0.25mm Draft @COREONEINDX HF0.4", "0.25mm DRAFT @CORE One INDX 0.4"),
    ],
    "filament": [
        ("Prusament PLA @COREONEINDX HF0.4", "Prusament PLA @CORE One INDX"),
        ("Prusament PLA Blend @COREONEINDX HF0.4", "Prusament PLA Blend @CORE One INDX"),
        ("Prusament rPLA @COREONEINDX HF0.4", "Prusament rPLA @CORE One INDX"),
        ("Prusament Woodfill @COREONEINDX HF0.4", "Prusament Woodfill @CORE One INDX"),
        ("Prusament PETG @COREONEINDX HF0.4", "Prusament PETG @CORE One INDX"),
        ("Prusament ASA @COREONEINDX HF0.4", "Prusament ASA @CORE One INDX"),
        ("Prusament PC Blend @COREONEINDX HF0.4", "Prusament PC Blend @CORE One INDX"),
        ("Prusament PC Blend Carbon Fiber @COREONEINDX HF0.4", "Prusament PC Blend Carbon Fiber @CORE One INDX"),
        ("Generic PLA @COREONEINDX HF0.4", "Generic PLA @CORE One INDX"),
        ("Generic PLA Silk @COREONEINDX HF0.4", "Generic PLA Silk @CORE One INDX"),
        ("Generic PETG @COREONEINDX HF0.4", "Generic PETG @CORE One INDX"),
        ("Generic ABS @COREONEINDX HF0.4", "Generic ABS @CORE One INDX"),
    ],
}

# (ps_key, ps_value) -> the value the Orca profile must hold instead.
# Shrinkage: PS stores compensation percent, Orca stores measured-length percent
# (100 - compensation), per the filament_shrink tooltip in PrintConfig.cpp.
VALUE_TRANSFORMS = {
    ("machine_limits_usage", "emit_to_gcode"): "1",
    ("support_material_xy_spacing", "80%"): "0.36",
    ("support_material_interface_speed", "50%"): "60",
    ("arc_fitting", "emit_center"): "1",
    ("gcode_label_objects", "firmware"): "1",
    ("top_fill_pattern", "monotoniclines"): "monotonicline",
    ("top_one_perimeter_type", "top"): "1",
    ("ensure_vertical_shell_thickness", "enabled"): "ensure_all",
    ("filament_shrinkage_compensation_xy", "0.22%"): "99.78%",
    ("filament_shrinkage_compensation_xy", "0.18%"): "99.82%",
    ("filament_shrinkage_compensation_xy", "0%"): "100%",
    ("filament_shrinkage_compensation_z", "0.22%"): "99.78%",
    ("filament_shrinkage_compensation_z", "0.18%"): "99.82%",
    # Orca idle_temperature is non-nullable coInts; 0 = "treat as unset" and the
    # start g-code guards it with `<= 0` where PS used is_nil().
    ("idle_temperature", "nil"): "0",
}
